# Generated by Django 4.1.3 on 2022-11-15 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemID', to='apis.ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='apis.ingredient'),
        ),
    ]
