# Generated by Django 4.1.3 on 2022-11-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_ingredient_item_id_alter_ingredient_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemID', to='apis.item'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderID', to='apis.order'),
        ),
    ]
