# Generated by Django 4.1.3 on 2022-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_post_image_url_post_link_only_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salt',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
