# Generated by Django 4.1.3 on 2023-02-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_rename_salt_post_slug_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_quantity', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='cuisine',
            field=models.CharField(default='Italian', max_length=200),
        ),
    ]
